sudo: false
language: node_js
node_js:
  - "4.0"
  - "4.4"
  - "5.0"
  - "6.0"

script:
- npm run test
- npm run test-referee

notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: never
  email: false
